
name: Evoluto_AI
description: Analizza bilanci aziendali e fornisce bandi compatibili.
model: gpt-3.5
tools:
  - type: file_upload
    accept:
      - application/pdf
      - application/vnd.openxmlformats-officedocument.wordprocessingml.document
  - type: api
    method: POST
    url: https://evoluto-app-wa89.onrender.com/process
    name: Verifica Aziendale
    request:
      contentType: application/json
      fields:
        - name: folder_id
          type: string
          required: true
        - name: azienda
          type: string
          required: true
