name: Trigger Render every 5 minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # ogni 5 minuti
  workflow_dispatch:       # consente anche l’avvio manuale

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render Endpoint
        run: |
          curl -X POST https://evoluto-app-wa89.onrender.com/trigger
