name: Trigger Render every 60 minutes

on:
  schedule:
  - cron: '0 * * * *'  # ogni ora
  workflow_dispatch:       # consente anche l’avvio manuale

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Send trigger to Render
        run: curl -X POST https://evoluto-app-wa89.onrender.com/trigger
