name: Aggiorna bandi JSON

on:
  schedule:
    - cron: '0 2 * * *'  # Ogni giorno alle 2:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Imposta Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Installa dipendenze
        run: pip install requests pandas

      - name: Scarica dati da Supabase
        run: |
          python scarica_bandi.py

      - name: Commit e Push
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add opendata-export.json
          git commit -m "Aggiornamento automatico bandi JSON"
          git push
