[server]
headless = true
port = 8501
enableCORS = true
enableXsrfProtection = true

[theme]
base = "light"
primaryColor = "#1E88E5"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#000000"
font = "sans serif"
